version: "3.9"
services:
    app:
        build:
            dockerfile: Dockerfile.dev
            context: .
            target: dev
        ports:
            -   "80:8080"
        environment:
            - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
            - MONGODB_URI=${MONGODB_URI}
            - GOOGLE_CLOUD_STORAGE_BUCKET=${GOOGLE_CLOUD_STORAGE_BUCKET}
            - MONGO_DB_DATABASE=${MONGO_DB_DATABASE}
            - MONGO_DB_SEARCH_INDEX=${MONGO_DB_SEARCH_INDEX}
        volumes:
            - .:/opt/app/api
